# Generated by Django 5.1.5 on 2026-03-10 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_application_milestone_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.grant'),
        ),
    ]
