# Generated by Django 5.1.5 on 2026-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0004_alter_application_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
