# Generated by Django 5.1.5 on 2026-03-26 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=200)),
                ('device', models.CharField(blank=True, max_length=220)),
                ('user_agent', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('locale', models.CharField(blank=True, max_length=32)),
                ('client_timezone', models.CharField(blank=True, max_length=80)),
                ('connected_at_client', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
